name: pop
description: "POP - Shop from your favorite stores"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  provider: ^6.1.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  lottie: ^3.1.0
  share_plus: ^7.2.2
  mobile_scanner: ^6.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  http: ^1.2.0
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.4.4
  google_sign_in: ^6.2.2
  cloud_functions: ^5.2.4
  
  # Payment
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  
  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.3
  path_provider: ^2.1.5
  
  # Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#fb2a0a"
  image: assets/images/popstoreslogo.PNG
  android: true
  ios: true
  android_12:
    color: "#fb2a0a"
    image: assets/images/popstoreslogo.PNG

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/popstoreslogo.PNG"
  adaptive_icon_background: "#EB1700"
  adaptive_icon_foreground: "assets/images/popstoreslogo.PNG"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/animations/
